# This code still needs to restart the helloworld application after install
version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: Scripts/start_server
      timeout: 180
