# This code still needs to restart the helloworld application after install
version: 0.0
os: linux
files:
  - source: /myapp
    destination: /home/ubuntu/helloworld/
hooks:
  AferInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  